//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// FileUploader
    /// </summary>
    [Serializable]
    public partial class FileUploader
    {
    public FileUploader()
        {
    	}
    			    /// <summary>
        /// 主键
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "主键")]
        [MaxLength(36,ErrorMessage="最多只能输入36个字符")]
        [StringLength(36,ErrorMessage="最多只能输入36个字符")]
        [Key]
    
        public string Id { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        [Display(Name = "名称")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string Name { get; set; }
        /// <summary>
        /// 路径
        /// </summary>
        [Display(Name = "路径")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string Path { get; set; }
        /// <summary>
        /// 全路径
        /// </summary>
        [Display(Name = "全路径")]
        [MaxLength(500,ErrorMessage="最多只能输入500个字符")]
        [StringLength(500,ErrorMessage="最多只能输入500个字符")]
    
        public string FullPath { get; set; }
        /// <summary>
        /// 后缀
        /// </summary>
        [Display(Name = "后缀")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string Suffix { get; set; }
        /// <summary>
        /// 大小
        /// </summary>
        [Display(Name = "大小")]
    
        public int? Size { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [Display(Name = "备注")]
        [MaxLength(4000,ErrorMessage="最多只能输入4000个字符")]
        [StringLength(4000,ErrorMessage="最多只能输入4000个字符")]
    
        public string Remark { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        [Display(Name = "状态")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string State { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Display(Name = "创建时间")]
        [DataType(DataType.DateTime)]
    
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        [Display(Name = "创建人")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string CreatePerson { get; set; }
    }
}
