//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public Nullable<decimal> Chinese { get; set; }
        public Nullable<decimal> Math { get; set; }
        public Nullable<decimal> English { get; set; }
        public string PictruePath { get; set; }
        public int ClassId { get; set; }
    
        public virtual ClassTab ClassTab { get; set; }
    }
}
