//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// Student
    /// </summary>
    [Serializable]
    public partial class Student
    {
        /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? Age { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(10,ErrorMessage="最多只能输入10个字符")]
        [StringLength(10,ErrorMessage="最多只能输入10个字符")]
        public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? Sex { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal? Chinese { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal? Math { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public decimal? English { get; set; }
    
       
         public virtual ICollection<Attributes> Attributes { get; set; }
    }
}
