//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// SysDocumentSysDepartment
    /// </summary>
    [Serializable]
    public partial class SysDocumentSysDepartment
    {
    public SysDocumentSysDepartment()
        {
    	}
    			    /// <summary>
        /// Id
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "Id")]
        [MaxLength(36,ErrorMessage="最多只能输入36个字符")]
        [StringLength(36,ErrorMessage="最多只能输入36个字符")]
        [Key]
    
        public string Id { get; set; }
        /// <summary>
        /// SysDepartmentId
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "SysDepartmentId")]
        [MaxLength(36,ErrorMessage="最多只能输入36个字符")]
        [StringLength(36,ErrorMessage="最多只能输入36个字符")]
    
        public string SysDepartmentId { get; set; }
        /// <summary>
        /// SysDocumentId
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "SysDocumentId")]
        [MaxLength(36,ErrorMessage="最多只能输入36个字符")]
        [StringLength(36,ErrorMessage="最多只能输入36个字符")]
    
        public string Sys_Id { get; set; }
    }
}
