//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// SysMenu
    /// </summary>
    [Serializable]
    public partial class SysMenu
    {
    public SysMenu()
        {
    	}
    			    /// <summary>
        /// 主键
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "主键")]
        [MaxLength(36,ErrorMessage="最多只能输入36个字符")]
        [StringLength(36,ErrorMessage="最多只能输入36个字符")]
        [Key]
    
        public string Id { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "名称")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string Name { get; set; }
        /// <summary>
        /// 父模块
        /// </summary>
        [Display(Name = "父模块")]
        [MaxLength(36,ErrorMessage="最多只能输入36个字符")]
        [StringLength(36,ErrorMessage="最多只能输入36个字符")]
    
        public string ParentId { get; set; }
        /// <summary>
        /// 网址
        /// </summary>
        [Display(Name = "网址")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string Url { get; set; }
        /// <summary>
        /// 图标
        /// </summary>
        [Display(Name = "图标")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string Iconic { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        [Display(Name = "排序")]
    
        public int? Sort { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [Display(Name = "备注")]
        [MaxLength(4000,ErrorMessage="最多只能输入4000个字符")]
        [StringLength(4000,ErrorMessage="最多只能输入4000个字符")]
    
        public string Remark { get; set; }
        /// <summary>
        /// 展开或折叠
        /// </summary>
        [Display(Name = "展开或折叠")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string State { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        [Display(Name = "创建人")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string CreatePerson { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Display(Name = "创建时间")]
        [DataType(DataType.DateTime)]
    
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
        /// 编辑时间
        /// </summary>
        [Display(Name = "编辑时间")]
        [DataType(DataType.DateTime)]
    
        public System.DateTime? UpdateTime { get; set; }
        /// <summary>
        /// 编辑人
        /// </summary>
        [Display(Name = "编辑人")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string UpdatePerson { get; set; }
        /// <summary>
        /// 是否是子节点
        /// </summary>
        [Display(Name = "是否是子节点")]
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string IsLeaf { get; set; }
    }
}
