//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// TB_Department
    /// </summary>
    [Serializable]
    public partial class TB_Department
    {
        /// <summary>
        /// 部门ID
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "部门ID")]
        [Key]
        public int department_id { get; set; }
        /// <summary>
        /// 部门名称
        /// </summary>
        [Display(Name = "部门名称")]
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
        public string department_name { get; set; }
        /// <summary>
        /// 父级名称
        /// </summary>
        [Display(Name = "父级名称")]
        public int? parent_id { get; set; }
        /// <summary>
        /// 部门等级
        /// </summary>
        [Display(Name = "部门等级")]
        [MaxLength(10,ErrorMessage="最多只能输入10个字符")]
        [StringLength(10,ErrorMessage="最多只能输入10个字符")]
        public string department_level { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        [Display(Name = "状态")]
        [MaxLength(10,ErrorMessage="最多只能输入10个字符")]
        [StringLength(10,ErrorMessage="最多只能输入10个字符")]
        public string status { get; set; }
    }
}
