//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MenuRole
    {
        public int id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string role_type { get; set; }
        public string button_id { get; set; }
    
        public virtual TB_Menu TB_Menu { get; set; }
        public virtual TB_Role TB_Role { get; set; }
    }
}
