//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// TB_Menu
    /// </summary>
    [Serializable]
    public partial class TB_Menu
    {
    public TB_Menu()
        {
            this.TB_MenuRole = new HashSet<TB_MenuRole>();
    	}
    			    /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Key]
    
        public int menu_id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
    
        public string menu_name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
    
        public string menu_url { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
    
        public string parent_id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(10,ErrorMessage="最多只能输入10个字符")]
        [StringLength(10,ErrorMessage="最多只能输入10个字符")]
    
        public string menu_level { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
    
        public string sort_order { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(10,ErrorMessage="最多只能输入10个字符")]
        [StringLength(10,ErrorMessage="最多只能输入10个字符")]
    
        public string status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(1000,ErrorMessage="最多只能输入1000个字符")]
        [StringLength(1000,ErrorMessage="最多只能输入1000个字符")]
    
        public string remark { get; set; }
    
       
         public virtual ICollection<TB_MenuRole> TB_MenuRole { get; set; }
    }
}
