//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// TB_Role
    /// </summary>
    [Serializable]
    public partial class TB_Role
    {
            /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Key]
        public int role_id { get; set; }
            /// <summary>
        /// 
        /// </summary>
        [MaxLength(50)]
        [StringLength(50)]
        public string role_name { get; set; }
            /// <summary>
        /// 
        /// </summary>
        [MaxLength(500)]
        [StringLength(500)]
        public string description { get; set; }
            /// <summary>
        /// 
        /// </summary>
        [DataType(DataType.DateTime)]
        public System.DateTime? createtime { get; set; }
            /// <summary>
        /// 
        /// </summary>
        [DataType(DataType.DateTime)]
        public System.DateTime? modifytime { get; set; }
    
       
         public virtual ICollection<TB_MenuRole> TB_MenuRole { get; set; }
       
         public virtual ICollection<TB_UserRole> TB_UserRole { get; set; }
    }
}
