//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// TB_Role
    /// </summary>
    [Serializable]
    public partial class TB_Role
    {
        /// <summary>
        /// 角色ID
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "角色ID")]
        [Key]
        public int role_id { get; set; }
        /// <summary>
        /// 角色名称
        /// </summary>
        [Display(Name = "角色名称")]
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
        public string role_name { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        [Display(Name = "描述")]
        [MaxLength(500,ErrorMessage="最多只能输入500个字符")]
        [StringLength(500,ErrorMessage="最多只能输入500个字符")]
        public string description { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Display(Name = "创建时间")]
        [DataType(DataType.DateTime)]
        public System.DateTime? createtime { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        [Display(Name = "修改时间")]
        [DataType(DataType.DateTime)]
        public System.DateTime? modifytime { get; set; }
    
       
         public virtual ICollection<TB_MenuRole> TB_MenuRole { get; set; }
       
         public virtual ICollection<TB_UserRole> TB_UserRole { get; set; }
    }
}
