//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// TB_Users
    /// </summary>
    [Serializable]
    public partial class TB_Users
    {
            /// <summary>
        /// 用户ID
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "用户ID")]
        [Key]
        public int user_id { get; set; }
            /// <summary>
        /// 用户名
        /// </summary>
        [Display(Name = "用户名")]
        [MaxLength(50)]
        [StringLength(50)]
        public string user_name { get; set; }
            /// <summary>
        /// 密码
        /// </summary>
        [Display(Name = "密码")]
        [MaxLength(50)]
        [StringLength(50)]
        [DataType(DataType.Password)]
        public string user_password { get; set; }
            /// <summary>
        /// 全名
        /// </summary>
        [Display(Name = "全名")]
        [MaxLength(50)]
        [StringLength(50)]
        public string fullname { get; set; }
            /// <summary>
        /// 部门名称
        /// </summary>
        [Display(Name = "部门名称")]
        public int? department_id { get; set; }
            /// <summary>
        /// 状态
        /// </summary>
        [Display(Name = "状态")]
        [MaxLength(10)]
        [StringLength(10)]
        public string status { get; set; }
            /// <summary>
        /// 创建时间
        /// </summary>
        [Display(Name = "创建时间")]
        [DataType(DataType.DateTime)]
        public System.DateTime? createtime { get; set; }
            /// <summary>
        /// 修改时间
        /// </summary>
        [Display(Name = "修改时间")]
        [DataType(DataType.DateTime)]
        public System.DateTime? modifytime { get; set; }
            /// <summary>
        /// 备注
        /// </summary>
        [Display(Name = "备注")]
        [MaxLength(1000)]
        [StringLength(1000)]
        public string remark { get; set; }
            /// <summary>
        /// 图片url
        /// </summary>
        [Display(Name = "图片url")]
        [MaxLength(200)]
        [StringLength(200)]
        public string url { get; set; }
    
       
         public virtual ICollection<TB_UserRole> TB_UserRole { get; set; }
    }
}
