//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// TB_Users
    /// </summary>
    [Serializable]
    public partial class TB_Users
    {
    public TB_Users()
        {
            this.TB_UserRole = new HashSet<TB_UserRole>();
    	}
    			    /// <summary>
        /// 
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Key]
    
        public int user_id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
    
        public string user_name { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
        [DataType(DataType.Password)]
    
        public string user_password { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(50,ErrorMessage="最多只能输入50个字符")]
        [StringLength(50,ErrorMessage="最多只能输入50个字符")]
    
        public string fullname { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public int? department_id { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(10,ErrorMessage="最多只能输入10个字符")]
        [StringLength(10,ErrorMessage="最多只能输入10个字符")]
    
        public string status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataType(DataType.DateTime)]
    
        public System.DateTime? createtime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataType(DataType.DateTime)]
    
        public System.DateTime? modifytime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(1000,ErrorMessage="最多只能输入1000个字符")]
        [StringLength(1000,ErrorMessage="最多只能输入1000个字符")]
    
        public string remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [MaxLength(200,ErrorMessage="最多只能输入200个字符")]
        [StringLength(200,ErrorMessage="最多只能输入200个字符")]
    
        public string url { get; set; }
    
       
         public virtual ICollection<TB_UserRole> TB_UserRole { get; set; }
    }
}
