//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Oralce
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// NEWTABLE
    /// </summary>
    [Serializable]
    public partial class NEWTABLE
    {
    public NEWTABLE()
        {
    	}
    			    /// <summary>
        /// N_ID
        /// </summary>
        [Required(ErrorMessage = "请输入{0}")]
        [Display(Name = "N_ID")]
        [MaxLength(36,ErrorMessage="最多只能输入36个字符")]
        [StringLength(36,ErrorMessage="最多只能输入36个字符")]
        [Key]
    
        public string N_ID { get; set; }
        /// <summary>
        /// 泵站ID
        /// </summary>
        [Display(Name = "泵站ID")]
        [MaxLength(32,ErrorMessage="最多只能输入32个字符")]
        [StringLength(32,ErrorMessage="最多只能输入32个字符")]
    
        public string S_DRAI_PUMP_ID { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        [Display(Name = "名称")]
        [MaxLength(38,ErrorMessage="最多只能输入38个字符")]
        [StringLength(38,ErrorMessage="最多只能输入38个字符")]
    
        public string S_SNAME { get; set; }
        /// <summary>
        /// 类型
        /// </summary>
        [Display(Name = "类型")]
    
        public decimal? N_DRAI_PUMP_TYPE { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public decimal? N_DRAI_PUMP_TYPE_FEAT { get; set; }
        /// <summary>
        /// 时间
        /// </summary>
        [Display(Name = "时间")]
        [DataType(DataType.DateTime)]
    
        public System.DateTime? T_STIME { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public decimal? N_LIULIANG { get; set; }
        /// <summary>
        /// 雨量
        /// </summary>
        [Display(Name = "雨量")]
    
        public decimal? N_YULIANG { get; set; }
        /// <summary>
        /// 水位
        /// </summary>
        [Display(Name = "水位")]
    
        public decimal? N_SHUIWEI { get; set; }
        /// <summary>
        /// 台数
        /// </summary>
        [Display(Name = "台数")]
    
        public decimal? N_TAISHU { get; set; }
        /// <summary>
        /// 开机台数
        /// </summary>
        [Display(Name = "开机台数")]
    
        public decimal? N_KAIJITAISHU { get; set; }
        /// <summary>
        /// 液位
        /// </summary>
        [Display(Name = "液位")]
    
        public decimal? N_YEWEI { get; set; }
        /// <summary>
        /// 外液位
        /// </summary>
        [Display(Name = "外液位")]
    
        public decimal? N_WAIYEWEI { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public short? N_RUNNING { get; set; }
    }
}
